plot4  <-  function(){
  data  <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
  data1  <- subset(data, as.Date(data$Date, "%d/%m/%Y")=="2007-02-01"| as.Date(data$Date, "%d/%m/%Y")=="2007-02-02")
  y  <- mapply(function(a, b) paste(a, b), data1[1:2880,1], data1[1:2880,2])
  z <- strptime(y, "%d/%m/%Y %H:%M:%S")
  png("plot4.png")
  par(mfrow = c(2, 2))
  hist(data1[,3], col = "red", main = "Global Active Power", xlab ="Global Active Power(kilowatts)")
  plot(z, data1[,7], xlab = "", ylab = "Energy sub metering", type = "n")
  legend("topright", lty = c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
  lines(z, data1[,7])
  plot(z, data1[,5],  xlab = "datetime", ylab = "Voltage", type = "n")
  lines(z, data1[,5])
  par(mfrow = c(2, 2))
  plot(z, data1[,3],  xlab = "", ylab = "Global Active Power(kilowatts)", type = "n")
  lines(z, data1[,3])
  plot(z, data1[,5],  xlab = "datetime", ylab = "Voltage", type = "n")
  lines(z, data1[,5])
  plot(z, data1[,7], xlab = "", ylab = "Energy sub metering", type = "n")
  legend("topright", lty = c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
  lines(z, data1[,9], col = "blue")
  lines(z, data1[,8], col = "red")
  lines(z, data1[,7])
  plot(z, data1[,4],  xlab = "datetime", ylab = "Global_reactive_power", type = "n")
  lines(z, data1[,4])
  dev.off()
}